eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

message: Hello

---
spring:
  profiles: service1

server:
  port: 8081

---
spring:
  profiles: service2

server:
  port: 8082